source 'https://rubygems.org'
require 'rubygems'

gem 'pg'
gem 'pry'
gem 'puma'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'json'
gem 'sinatra'
gem 'sinatra-formhelpers-ng', '~> 1.9', '>= 1.9.1'
gem 'sinatra-flash'
